# Generated by Django 4.2.3 on 2023-10-12 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='formdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('dob', models.DateField()),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('phone', models.IntegerField()),
                ('address', models.CharField(max_length=500)),
                ('department', models.CharField(max_length=50)),
                ('courses', models.CharField(max_length=50)),
            ],
        ),
    ]
