# Generated by Django 4.2.3 on 2023-10-13 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_department_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formdb',
            old_name='courses',
            new_name='course',
        ),
        migrations.AddField(
            model_name='formdb',
            name='email',
            field=models.CharField(default='hsdg', max_length=100),
            preserve_default=False,
        ),
    ]
