# Generated by Django 4.2.3 on 2023-10-13 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_rename_courses_formdb_course_formdb_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formdb',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
